### ISSUE TITLE
Error php while using the single page format

### ISSUE THREAD

**Issue by sp0ker** [dauxio/daux.io#30]
Hi,
I use v0.7.0.

When i try to generate my documentation with the format html-file (single file)
`daux generate --format=html-file`

I get this error : 
`PHP Warning:  file_get_contents(themes/daux_singlepage/css/main.min.css): failed to open stream: No such file or directory in /home/remi/.config/composer/vendor/justinwalsh/daux.io/libs/Format/HTMLFile/Book.php on line 22`

In my static folder i verify if i have the css and it's ok : `static/themes/daux_singlepage/css/main.min.css.`

The function where the code fail is in [this file](https://github.com/dauxio/daux.io/blob/master/libs/Format/HTMLFile/Book.php) at line 22 : 
```php
protected function getStyles()
    {
        // TODO :: un-hardcode that
        return '<style>' . file_get_contents('themes/daux_singlepage/css/main.min.css') . '</style>';
    }
```

**Comment by onigoetz** [comment]
Hello
By the path you show me, you are using `justinwalsh/daux.io` which is the old tool's name.

Can you try to use `composer global require daux/daux.io` and remove `justinwalsh/daux.io` ?

I've made some bugfixes to single page documentation generate in version 0.7.1, maybe you can have a look at them ?

**Comment by sp0ker** [comment]
Hi,
I download your latest release (v0.7.1) and done  : `daux generate --format=html-file`

But i get this errors : 
```shell
daux generate --format=html-file
Generating MétaDoc Rémi                                                                                                                                                                           [  OK  ]
Generating Architecture                                                                                                                                                                           [  OK  ]
Generating Adressage Ip                                                                                                                                                                           [  OK  ]
Generating Mon Compte Internet                                                                                                                                                                    [  OK  ]
Generating Alcasar                                                                                                                                                                                [  OK  ]
Generating Architecture HA TESTPHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/Base/EmbedImages.php:41
Stack trace:
#0 /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/Base/EmbedImages.php(75): Todaymade\Daux\Format\Base\EmbedImages->getAttributes('<img src="image...')
#1 /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/Base/EmbedImages.php(29): Todaymade\Daux\Format\Base\EmbedImages->findImage('images/schema1....', '<img src="image...', Object(Todaymade\Daux\Tree\Raw), Object(Closure))
#2 [internal function]: Todaymade\Daux\Format\Base\EmbedImages->Todaymade\Daux\Format\Base\{closure}(Array)
#3 /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/Base/EmbedImages.php(35): preg_replace_callback('/<img\\s+[^>]*sr...', Object(Closure), '<h2 id="page_Ar...')
#4 /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/HTMLFile/ContentPage.php(28): Todaymade\Daux\Format\Base\EmbedImages->embed('<h2 id="page_Ar...', Object(Todaymade\Daux\Tree\Content), O in /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/Base/EmbedImages.php on line 41
```

**Comment by onigoetz** [comment]
It seems you need the DOM extension for PHP. which version of PHP are you using ?

**Comment by sp0ker** [comment]
Yes i changed that. The `daux generate` command is correctly working.

But i still have problems with `daux generate --format=html-file` : 
```php
Generating Projets FutursPHP Notice:  Undefined index: theme in /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/HTML/Template.php on line 31
PHP Warning:  file_get_contents(themes/daux_singlepage/css/main.min.css): failed to open stream: No such file or directory in /home/remi/.config/composer/vendor/daux/daux.io/libs/Format/HTMLFile/Book.p
hp on line 22
```
I keep watching this,

Thanks a lot,
Rémi

**Comment by onigoetz** [comment]
I'll have a look at this in the coming days

**Comment by onigoetz** [comment]
Hello, I'm very sorry for the delay on this issue, I fixed the generation of single-page documentation, it's on the master branch currently and will be released in a few days
