### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method League\CommonMark\HtmlRenderer::escape() in daux/Markdown/FencedCodeRenderer.php:31

### ISSUE THREAD

**Issue by Elendev** [dauxio/daux.io#82]
Hello,

There is an issue in the version `0.8.1` of Daux. When I try to build the documentation I get the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method League\CommonMark\HtmlRenderer::escape() in daux/Markdown/FencedCodeRenderer.php:31
Stack trace:
#0 vendor/league/commonmark/src/HtmlRenderer.php(96): Todaymade\Daux\Extension\Markdown\FencedCodeRenderer->render(Object(League\CommonMark\Block\Element\FencedCode), Object(League\CommonMark\HtmlRenderer), false)
#1 vendor/league/commonmark/src/HtmlRenderer.php(109): League\CommonMark\HtmlRenderer->renderBlock(Object(League\CommonMark\Block\Element\FencedCode), false)
#2 vendor/league/commonmark/src/Block/Renderer/DocumentRenderer.php(36): League\CommonMark\HtmlRenderer->renderBlocks(Array)
#3 vendor/league/commonmark/src/HtmlRenderer.php(96): League\CommonMark\Block\Renderer\DocumentRenderer->render(Object(League\CommonMark\Block\Element\Document), Object(League\CommonMark\HtmlRenderer), false)
#4 in /home/jonas/workspace/github.bank/sq/sq-web-components-core/packages/styleguide/daux/Markdown/FencedCodeRenderer.php on line 31
```
This issue might be related to the upgrade of `League\CommonMark` dependency update that I see here: https://github.com/dauxio/daux.io/compare/d1089b114e43cbc1d04718f84890db1e1dbc05c9...7d8d5c86cfce682166bb55bc2298f2658c75cdc3#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L22

Precisely to this commit: https://github.com/thephpleague/commonmark/commit/da2c524f39781210ecd8d2b5870acdfc3acfc36b#diff-9c5cf6be950d9aa2c48461dabc31ab57

They have moved the `escape` method to a static helper.

**Comment by onigoetz** [comment]
Fixed in daux 0.9.0
